### ISSUE TITLE
Undefined variable $revision in DocumentHandler.php line 705

### ISSUE THREAD

**Issue by diabl0** [arangodb/arangodb-php#199]
https://github.com/arangodb/arangodb-php/blob/master/lib/triagens/ArangoDb/DocumentHandler.php#L705

adding $revision = `$document->getRevision();` before this line fixed the problem.

**Comment by frankmayer** [comment]
Thanks for taking the time to report.
This one was already fixed in in devel but did not make it to master yet.
Commit: c259963fec2b3846ef5ef89e1b0ad3709d0b7ad9
I will hopefully release a new 3.0.x version within the next couple of days, which will include this and other fixes and improvements.
Closing this for now. If there is anything else concerning this, feel free to comment.

PS: Release 3.1 of the driver will finally have the very old deprecated stuff removed, which unfortunately wasn't removed in 2.x and 3.0. This in turn will allow for some refactoring and improvements further down the road.
