### ISSUE TITLE
Incorrect logic in Cursor constructor

### ISSUE THREAD

**Issue by msukhov** [arangodb/arangodb-php#205]
Cursor.php

Line 188: `if (isset($data[self::ENTRY_EXTRA])) {`
...
Line 195: `} else if (isset($data[self::ENTRY_EXTRA][self::FULL_COUNT])) {`

**Comment by frankmayer** [comment]
Thanks for reporting. I'll take a look.

**Comment by frankmayer** [comment]
So, this is of course a logic error. Nice catch. :)

However, it will only be a problem if a pre 2.3 ArangoDB version is used. Are you using a pre 2.3 version of ArangoDB and a pre 3.0 PHP driver?

Since the 3.x driver only supports ArangoDB 3.x and higher, this will not affect the new driver.

I will clean it up for the 3.x drivers, though.

**Comment by frankmayer** [comment]
Closing as fix exists in devel branch and has no effect on the 3.x line, whatsoever.

**Comment by msukhov** [comment]
I'm just installed ArangoDB and truing to use it in my project... of course latest version)
For the moment i'm reading manuals and php driver sources...

One of the Good Point of ArangoDB, that i've noticed, that it loads 5M documents (with 100+ fields and ~15 indixes) during about 7 minutes. For example TokuDB loads same dataset during about 35 minutes.
