### ISSUE TITLE
ArangoDB issue with server cores.

### ISSUE THREAD

**Issue by eafiontzi** [arangodb/arangodb-php#238]
Hi all,
We are experiencing a kind of weird problem. Our application runs on a cuad-core server for arangodb and sometimes is really slow (we have a pageTree graph with about 4.000 edges). We tried updating to octa-core in the virtual server, but it resulted to even slower and sometimes crashing the application. Does anyone have any idea regarding that? Are there any parameters in the configuration file that need changing when adding cores? I attach two images from my server htop before and after the change in cores.
Thank you all in advance
![8cores](https://user-images.githubusercontent.com/14819444/37024957-0ce1ecbe-2133-11e8-964d-78f251ea5f3a.png)
![4cores](https://user-images.githubusercontent.com/14819444/37024958-0d054362-2133-11e8-8646-6600f48602fd.png)

**Comment by jsteemann** [comment]
It is actually hard to tell without further info what is going on.
At least some basic description of the setup (cluster vs. single server, ArangoDB version, storage engine) plus the workload would be appreciated.
I am not sure is this issue is actually driver-related, so it may be more useful to open this issue with the missing info in the ArangoDB main repository (https://github.com/arangodb/arangodb/issues) or in our Slack channel.

**Comment by eafiontzi** [comment]
Thanks a lot for the answer, the issue is probably not driver-related I will move it to the main repository
