### ISSUE TITLE
[BUG?] edgeHander->updateById

### ISSUE THREAD

**Issue by lshaf** [arangodb/arangodb-php#242]
Hi,

seems there's a problem when you update edge using edgeHander->updateById.
When I tried it, it does update but value of _from and _to node become null.

For now I can handle it by put _from and _to node when I update edge using edgeHander->updateById.
My question is, is that how it's work or maybe it's bug?

**Comment by jsteemann** [comment]
Thanks for raising this issue.
I just pushed a fix for this to the repository for the 3.3 branch: https://github.com/arangodb/arangodb-php/commit/31740b28ed3b87082c2eb2cb69b80cc38dec7d0f

**Comment by lshaf** [comment]
thanks. I will try it :)

**Comment by lshaf** [comment]
When I update my composer, it does nothing on arangodb.
Btw I'm using 3.3.2 version when I check it on my composer.lock

**Comment by jsteemann** [comment]
I didn't build a new release yet. The fix was only in the above commit.
I now created a new tag for the driver, which should be v3.3.9.
(note that there is a leap in version numbers, but the driver version numbers should resemble the latest ArangoDB server version numbers, which currently is at 3.3.9).
If you poll for updates, a new driver version should hopefully become available via composer soon.

**Comment by lshaf** [comment]
Thanks, it's been fixed :)

**Comment by frankmayer** [comment]
@jsteemann Long time no see :) 
Actually, according to the wiki, we only kept the major and minor version on par with ArangoDB itself and reserved the patch version for the client itself. So, the version should have been 3.3.3 instead of 3.3.9
Sorry, wasn't following the whole thing. Just noticed it.
Have a good one.

**Comment by jsteemann** [comment]
@frankmayer : oh sorry, I wasn't aware of that :smile:. Probably I should read our own wiki first.
