### ISSUE TITLE
Combine add() and update() to store().

### ISSUE THREAD

**Issue by F21** [arangodb/arangodb-php#32]
Currently, there are separate methods for `add()`ing and `update()`ing documents.

I think the API can be cleaner if we just have a `store()` method. A readonly property inside the `Document` class can provide information on whether the document should be added or updated.

What do you think?

**Comment by frankmayer** [comment]
So, finally closing this. The actual issue was resolved and the saveOrReplace() functionality is today implemented through the UPSERT AQL operation. Since there is no direct HTTP API for this, the only way of doing this in the driver would be to construct an AQL query. If there is still need for this, we may reopen the issue.
